pipeline {
    agent any
    environment {
        RELEASE='0.0.1'
    }
    stages{
        stage('Build') {
            agent any //e.g. if need a docker agent specifically, agent Docker
            environment{
                LOG_LEVEL='INFO'
            }
            parallel {
                stage('linux-arm64'){
                    steps {
                        echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
                    }
                }
                stage('linux-am64'){
                    steps {
                        echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
                    }
                }
                stage('windows-arm64'){
                    steps {
                        echo "Building release ${RELEASE} for ${STAGE_NAME} with log level ${LOG_LEVEL}"
                    }
                }
            }
        }
        stage('Test'){
            steps {
                echo "Testing. I can see release ${RELEASE}..."
            }
        }
        stage('Deploy'){
            input { //text box input, true false only
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment env')
                }
            }
            steps {
                echo "Deploying ${RELEASE} to env ${TARGET_ENVIRONMENT}"
            }
        }
    }
    post {
        always {
            echo 'Prints whether deploy happened or not, success or failure'
        }
        //if {}
    }
}